// This file was renamed from simulation-storage.js. All logic now uses forecast/Forecast naming conventions.
// ...existing code from simulation-storage.js, but with all simulation references changed to forecast...
